spring.application.name=auth-service
spring.jpa.defer-datasource-initialization=true
server.port=4005
spring.datasource.url=${SPRING_DATASOURCE_URL} 
spring.datasource.username=${SPRING_DATASOURCE_USERNAME} 
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD} 
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update} 
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
jwt.secret=${JWT_SECRET}