server:
  port: 4004

auth:
  service:
    url:${AUTH_SERVICE_URL}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri:  http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri:  http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-route
          uri:  http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - 'RewritePath=/api-docs/patients,/v3/api-docs'

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - 'RewritePath=/api-docs/auth,/v3/api-docs'

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    reactor.netty.http.client: DEBUG