pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REGISTRY = '774118824657.dkr.ecr.ap-south-1.amazonaws.com'
        ECR_REPOSITORY = '774118824657.dkr.ecr.ap-south-1.amazonaws.com/patient-service'
        AWS_CREDENTIALS = 'aws-patient-service'
        IMAGE_TAG = "${BUILD_NUMBER}"
        LAUNCH_TEMPLATE_ID = 'lt-0e1a3ca54608fee29'
        ASG_NAME = 'patient-service-asg'
        HEALTH_URL = 'http://patient-service-alb-677738985.ap-south-1.elb.amazonaws.com/actuator/health'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps
            {  withEnv([
                        'SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres',
                        'SPRING_DATASOURCE_USERNAME=postgres',
                        'SPRING_DATASOURCE_PASSWORD=postgres'
                    ]) {
                    dir('patient-service') {
                        sh '''
                        mvn -B clean test
                    '''
                    }}
            }
        }

        stage('Docker Build') {
            steps {
                dir('patient-service') {
                    echo "Building Docker image..."
                    sh '''
                        docker build --platform linux/amd64 \
                            -t ${ECR_REPOSITORY}:${IMAGE_TAG} .
                    '''
                    echo "Docker image built:"
                    // docker images ${ECR_REPOSITORY}:${IMAGE_TAG}
                }
            }
        }

        stage('ECR Login') {
            steps {
                withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${AWS_CREDENTIALS}"]
                    ]) {
                    sh '''
                        set -e
                        aws ecr get-login-password \
                            --region ${AWS_REGION} | \
                        docker login \
                            --username AWS \
                            --password-stdin ${ECR_REGISTRY}
                    '''
                }
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                    docker push ${ECR_REPOSITORY}:${IMAGE_TAG}
                '''
            }
        }

        stage('Create Launch Template Version') {
            steps {
                withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${AWS_CREDENTIALS}"]
                    ]) {
                    sh '''
                      set -e
                      echo "Creating Launch Template version"
                      echo "Launch Template ID: ${LAUNCH_TEMPLATE_ID}"
                      echo "Image tag: ${IMAGE_TAG}"
                      echo "Build number: ${BUILD_NUMBER}"


                      if [ -z "${LAUNCH_TEMPLATE_ID}" ]; then
                        echo "ERROR: LAUNCH_TEMPLATE_ID is empty"
                        exit 1
                      fi

                      if [ -z "${IMAGE_TAG}" ]; then
                        echo "ERROR: IMAGE_TAG is empty"
                        exit 1
                      fi

# Generate User Data with the image tag.
sed "s/__IMAGE_TAG__/${IMAGE_TAG}/g" \
    patient-service/aws/user-data.sh \
    > generated-user-data.sh

echo "Generated User Data successfully."

# Base64 encode User Data.
USER_DATA=$(base64 -w 0 generated-user-data.sh)

echo "Creating new Launch Template version..."

NEW_VERSION=$(aws ec2 create-launch-template-version \
    --launch-template-id "${LAUNCH_TEMPLATE_ID}" \
    --source-version '$Default' \
    --version-description "Jenkins build ${BUILD_NUMBER} - image ${IMAGE_TAG}" \
    --launch-template-data "{\"UserData\":\"${USER_DATA}\"}" \
    --region "${AWS_REGION}" \
    --query 'LaunchTemplateVersion.VersionNumber' \
    --output text)

if [ -z "${NEW_VERSION}" ] || [ "${NEW_VERSION}" = "None" ]; then
    echo "ERROR: Failed to create Launch Template version"
    exit 1
fi

echo "New Launch Template version: ${NEW_VERSION}"


                    }
                }
            }
        }

        stage('Update Auto Scaling Group') {
            steps {
                withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${AWS_CREDENTIALS}"]
                    ]) {
                    sh '''
                        set -e

                        NEW_VERSION=$(cat new_lt_version.txt)

                        echo "Updating ASG to Launch Template version ${NEW_VERSION}..."

                        aws autoscaling update-auto-scaling-group \
                            --auto-scaling-group-name ${ASG_NAME} \
                            --launch-template \
                                LaunchTemplateId=${LAUNCH_TEMPLATE_ID},Version=${NEW_VERSION} \
                            --region ${AWS_REGION}

                        echo "ASG updated successfully."
                    '''
                }
            }
        }

        stage('Start Instance Refresh') {
            steps {
                withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${AWS_CREDENTIALS}"]
                    ]) {
                    sh '''
                        set -e

                        echo "Starting Instance Refresh..."

                        REFRESH_ID=$(aws autoscaling start-instance-refresh \
                          --auto-scaling-group-name ${ASG_NAME} \
                          --preferences MinHealthyPercentage=100,InstanceWarmup=120 \
                          --region ${AWS_REGION} \
                          --query 'InstanceRefreshId' \
                          --output text)

                        echo "Instance Refresh started: ${REFRESH_ID}"

                        echo "${REFRESH_ID}" > refresh_id.txt
                    '''
                }
            }

        }
        stage('Wait For Deployment') {
            steps {
                withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${AWS_CREDENTIALS}"]
                    ]) {
                    sh '''
                        set -e

                        REFRESH_ID=$(cat refresh_id.txt)

                        echo "Waiting for Instance Refresh ${REFRESH_ID}..."

                        for i in $(seq 1 60); do

                            STATUS=$(aws autoscaling describe-instance-refreshes \
                                --auto-scaling-group-name ${ASG_NAME} \
                                --instance-refresh-ids ${REFRESH_ID} \
                                --region ${AWS_REGION} \
                                --query 'InstanceRefreshes[0].Status' \
                                --output text)

                            echo "Instance Refresh status: ${STATUS}"

                            case "$STATUS" in

                                Successful)
                                    echo "Deployment completed successfully."
                                    exit 0
                                    ;;

                                Failed|Cancelled|RollbackFailed)
                                    echo "Deployment failed with status: ${STATUS}"
                                    exit 1
                                    ;;

                                *)
                                    sleep 20
                                    ;;
                            esac

                        done

                        echo "Deployment timed out."
                        exit 1
                    '''
                }
            }
        }




        stage('Verify Deployment') {
            steps {
                script {
                    def healthUrl = 'http://patient-service-alb-677738985.ap-south-1.elb.amazonaws.com/actuator/health'

                    timeout(time: 3, unit: 'MINUTES') {
                        waitUntil {
                            def status = sh(
                                script: """
                            curl -s -o /tmp/health.json \
                                 -w "%{http_code}" \
                                 ${healthUrl}
                        """,
                                returnStdout: true
                            ).trim()

                            def response = sh(
                                script: "cat /tmp/health.json",
                                returnStdout: true
                            ).trim()

                            echo "HTTP Status: ${status}"
                            echo "Health Response: ${response}"

                            if (status == '200' && response.contains('"status":"UP"')) {
                                return true
                            }

                            echo "Application is not healthy yet. Waiting..."
                            sleep 10
                            return false
                        }
                    }

                    echo "Application health check passed."
                }
            }



            post {
                success {
                    echo "CI pipeline completed successfully."
                    echo "Image: ${ECR_REPOSITORY}:${IMAGE_TAG}"
                }

                failure {
                    echo "CI pipeline failed."
                }

                always {
                    sh 'docker logout ${ECR_REGISTRY} || true'

                }
            }
        }
    }
}