spring.application.name=patient-service

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.datasource.url=jdbc:h2:mem:testDB
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=sa
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5000/db?sslmode=disable}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.datasource.url=jdbc:postgresql://localhost:55432/db?sslmode=disable
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

server.port=4000
logging.level.root=info
spring.jpa.defer-datasource-initialization=true

billing.service.address=${BILLING_SERVICE_ADDRESS:localhost}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT:9001}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
